language: rust
rust: nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"

script:
    - ./scripts/build-all.sh
    - cargo test --features nightly
    - cargo bench --features nightly

notifications:
  webhooks: http://build.servo.org:54856/travis
